### ISSUE TITLE
IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by sagitaninta** [similab/FSTest#4]
Hi, I have been looking for a tool that can do window-based Hudson Fst so thanks for making this! 

I have a little hiccup though.

So when I ran:
```
python FSTest1.3.py --pop1 pop1.vcf --pop2 pop2.vcf --m 1 --win 100000 --step 100000 --mp 2 --o pop1.pop2.Hudson.FSTest
```

I got this error message, "`IndexError: single positional indexer is out-of-bounds`" which started from line 222 of the script when it processes the option `--mp 2`.

A more complete error message:
```
python FSTest1.3.py --pop1 pop1.vcf --pop2 pop2.vcf --m 1 --win 100000 --step 100000 --mp 2 --o pop1.pop2.Hudson.FSTest
**************************************************************
*                 FSTest software v 1.3                      *
*       Seyed Milad Vahedi, Siavash Salek Ardestani          *
*         smvahedi@dal.ca, siasia6650@gmail.com              *
**************************************************************
Elapsed time for processing SNPs: 702.52 s
Elapsed time for processing windows: 24.55 s
Traceback (most recent call last):
  File "/maps/projects/bos/people/mdn487/fst_imputed/FSTest/FSTest1.3.py", line 222, in <module>
    sugg3=sugg2[X].iloc[sugg1]
          ~~~~~~~~~~~~~^^^^^^^
  File "/home/mdn487/.conda/envs/scikit_env/lib/python3.11/site-packages/pandas/core/indexing.py", line 1153, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mdn487/.conda/envs/scikit_env/lib/python3.11/site-packages/pandas/core/indexing.py", line 1714, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/mdn487/.conda/envs/scikit_env/lib/python3.11/site-packages/pandas/core/indexing.py", line 1647, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

Do you know how I can fix it and get the window-based estimates?

**Comment by smiledv** [comment]
Hello. Thanks for using FSTest and reporting the issue. Please let me know if you get the same error if you remove the Manhattan plot parameter (--mp). You should get the results without the Manhattan plot when you remove it. I will work on that to see the issue with the Manhattan plot and get back to you as soon as possible.
